# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: classpath:/i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false
multipart:
    max-file-size: 100Mb
    max-request-size: 100Mb

# ===================================================================
# Apb specific properties
# ===================================================================

apb:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    #cors: #By default CORS are not enabled. Uncomment to enable.
        #allowed-origins: "*"
        #allowed-methods: GET, PUT, POST, DELETE, OPTIONS
        #allowed-headers: "*"
        #exposed-headers:
        #allow-credentials: true
        #max-age: 1800
    mail:
        from: Apb@localhost
    security:
        rememberme:
            # security key (this key should be unique for your application, and kept secret)
            key: 8b34865eeb9a8844ea2951ae80809e8cb05a0b0d
    swagger:
        title: Apb API
        description: Apb API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contact:
        license:
        licenseUrl:
